### ISSUE TITLE
SearchView

### ISSUE THREAD

**Issue by jaehoon9186** [jaehoon9186/SearchAPP#7]
## 🔍 Description
메인화면인 SearchView를 구성합니다. 

## 📝 Todo
- [x] Search bar(delegate, dismiss Keyboard, scope bar)
- [x] Search View 
- [x] Search ViewModel / Combine Input-Output pattern 적용 
- [x] child View 기본 구성, 전환
(suggestion(추천검색, 검색기록), WebResult, ImageResult, VideoResult)
- [x] child View tableview update (버튼 활성/비활성화 컴바인활용)
